### ISSUE TITLE
Javascript example?

### ISSUE THREAD

**Issue by amandapouget** [FaustXVI/functional-programming-introduction#1]
Salut Xavier !

J'ai raconté l'histoire du meetup où tu as presenté ce repo à Paris. Un de mes colleagues voulait voir l'exemple en javascript mais je ne trouve que les tests javascript, pas la code !

Puis-tu posté ce que suit le premier commit ?

Merci!

Amanda SIMON
visiteur americaine de la caroline du nord

**Comment by FaustXVI** [comment]
Bonjour Amanda,

Tout est commité sur la branche "playing" :)
N'hésitez pas à revenir vers moi si vous voulez que je vienne le rejouer en
live en bbl chez vous :)
Amusez vous bien !

Xavier Detant

On 12 Oct 2017 05:34, "Amanda Simon" <notifications@github.com> wrote:

Salut Xavier !

J'ai raconté l'histoire du meetup où tu as presenté ce repo à Paris. Un de
mes colleagues voulait voir l'exemple en javascript mais je ne trouve que
les tests javascript, pas la code !

Puis-tu posté ce que suit le premier commit ?

Merci!

Amanda SIMON
visiteur americaine de la caroline du nord

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/FaustXVI/functional-programming-introduction/issues/1>,
or mute the thread
